export { default as searchService } from './searchService'
export { default as topRated } from './topRatedService'
export { default as actionMovies } from './actionMovies'
export { default as comedyMovies } from './comedyMovies'
export { default as romanceMovies } from './romanceMovies'
export { default as horrorMovies } from './horrorMovies'
export { default as documentaries } from './documentaries'